project_id = "cknjyiukluuzaittclmr"

[functions.ai-interview]
verify_jwt = true

[functions.generate-interview-summary]
verify_jwt = true

[functions.elevenlabs-conversation-token]
verify_jwt = true

[functions.send-candidate-invite]
verify_jwt = false

[functions.improve-email-copy]
verify_jwt = true
